### ISSUE TITLE
Add support for custom domain

### ISSUE THREAD

**Issue by onedr0p** [DesicLabs/onepassword-web-client#4]
Currently the 1password api url is hard-coded to my.1password.com, it would be nice to add support for a custom domain.

**Comment by stevenroussey-privicy** [comment]
Is there another domain? Curious of the use case. There can be a way to hook the config, including the url.

**Comment by onedr0p** [comment]
Yes, family accounts and businesses can have their own 1password subdomain.

**Comment by onedr0p** [comment]
Project appears dead, closing.
